dist: bionic
language: go
go:
  - "1.13.x"

install:
  - sudo apt-get install -y zfsutils-linux && sudo modprobe zfs
  - go mod vendor
  - pushd ..; go get -u github.com/vbatts/git-validation; popd
  - pushd ..; go get -u github.com/kunalkushwaha/ltag; popd

before_script:
  - pushd ..; git clone https://github.com/containerd/project; popd

script:
  - DCO_VERBOSITY=-q ../project/script/validate/dco
  - ../project/script/validate/fileheader ../project/
  - sudo $GOROOT/bin/go test -test.root -test.v -race -covermode=atomic -coverprofile=coverage.txt ./...

after_success:
    - bash <(curl -s https://codecov.io/bash)
